// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file asset in the library.
 */
export type Asset = { id: string, kind: string, name: string, path: string, mime: string | null, byte_size: bigint | null, fingerprint: string | null, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, 
/**
 * Unix milliseconds, set when soft-deleted; `null` while live.
 */
deleted_at: bigint | null, };
