// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The canonical type of a library asset.
 *
 * Serialises as the variant name (PascalCase) so the TypeScript side receives
 * `"Logo"`, `"Template"`, etc. — matching the discriminated union in the
 * frontend.
 */
export type AssetKind = "Logo" | "Template" | "SongSheet" | "RecurringBlock" | "Font";
