// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an asset / image carried from the plan so the generated block
 * can later re-bind to the local asset library row by id, or fall back to a
 * URL the plan supplied.
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type AssetRef = { 
/**
 * Asset-library id, if the plan knew one.
 */
asset_id: string | null, 
/**
 * A URL / path the plan supplied (e.g. a poster the planner attached).
 */
url: string | null, 
/**
 * Alt text / caption for the image.
 */
caption: string | null, };
