// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetKind } from "./AssetKind";

/**
 * A library asset with the full Phase 1.3 metadata. Returned by all
 * `AssetLibRepo` operations.
 */
export type AssetLibEntry = { id: string, name: string, kind: AssetKind, file_path: string, 
/**
 * Comma-separated tag list — empty string means "no tags".
 */
tags: string, 
/**
 * Unix milliseconds.
 */
created_at: bigint, };
