// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportedFile } from "./ExportedFile";

/**
 * The summary a batch export returns: where the files went and the list of
 * each written PDF, in request order.
 */
export type BatchExportResult = { 
/**
 * The directory every file was written into.
 */
directory: string, 
/**
 * One entry per successfully exported document, in request order.
 */
files: Array<ExportedFile>, };
