// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One block to create, in order, on the generated program document. The
 * caller maps each to `BlockRepo::create(document_id, None, kind, data)`.
 */
export type BlockSpec = { 
/**
 * Block kind the app already renders (`heading`, `song`, `scripture`,
 * `liturgy`, `announcement`, `text`).
 */
kind: string, 
/**
 * Kind-specific payload, serialised as a JSON string (exactly what the
 * `block` table stores in its `data` column).
 */
data: string, };
