// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node in a document's block tree.
 */
export type Block = { id: string, document_id: string, 
/**
 * Parent block id; `null` for a top-level block.
 */
parent_id: string | null, kind: string, position: bigint, 
/**
 * Kind-specific payload as a JSON string.
 */
data: string, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, };
