// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateVar } from "./TemplateVar";

/**
 * A typed document template with Typst source and variable spec.
 */
export type DocTemplate = { id: string, name: string, kind: string, typst_source: string, 
/**
 * PNG thumbnail — `None` until explicitly generated / stored.
 */
preview_png: Array<number> | null, variables: Array<TemplateVar>, created_at: bigint, updated_at: bigint, deleted_at: bigint | null, };
