// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The high-level purpose of a document template.
 */
export type DocTemplateKind = "Bulletin" | "SongSheet" | "Magazine" | "Poster" | "Form" | "LargeText";
