// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document within a project. `kind` selects the document family (program,
 * song_sheet, magazine, poster, form); `position` orders it within the project.
 */
export type Document = { id: string, project_id: string, template_id: string | null, title: string, kind: string, page_size: string, position: bigint, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, 
/**
 * Unix milliseconds, set when soft-deleted; `null` while live.
 */
deleted_at: bigint | null, };
