// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutTheme } from "./LayoutTheme";

/**
 * Options applied to every document in a batch export. One option set, many
 * documents — the whole point of the feature.
 */
export type ExportOptions = { 
/**
 * Paper size keyword (`a4`, `a5`, `us-letter`, …). Empty / `null` keeps
 * each document's own page size. Normalised by `LayoutMeta`'s preamble, so
 * an unknown value still compiles (falls back to a4).
 */
paper: string | null, 
/**
 * Large-print font scaling, in percent of the base size. `100` (or `null`)
 * is regular size; `150` is the typical large-print sheet. Clamped to
 * 100–300%.
 */
largePrintPercent: number | null, 
/**
 * Optional Typst hyphenation language (`nb`, `en`, …) forwarded to the
 * document. `null` keeps Typst's default.
 */
lang: string | null, 
/**
 * Optional per-church branding (fonts / accent / spacing) applied to every
 * document in the batch. `null` keeps the house default look (an unthemed
 * preamble, byte-identical to no theme at all).
 */
theme: LayoutTheme | null, };
