// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a single document's export within a batch — surfaced so the
 * renderer can show per-document success/skip and the on-disk path.
 */
export type ExportedFile = { 
/**
 * The source document id this file was rendered from.
 */
documentId: string, 
/**
 * Absolute path of the written PDF.
 */
path: string, 
/**
 * The leaf filename (no directory) — handy for a compact UI list.
 */
fileName: string, };
