// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fillable-form block kinds the FormBuilder (Phase 7.2) adds on top of the
 * program block kinds. Unlike the program kinds these are not derived from a
 * [`ServicePlan`]; a volunteer composes them by hand (a signup sheet, an
 * attendance form, a donation card). Each maps to one block kind the layout
 * engine renders as a *printed* field — a labelled rule or box a person fills
 * in by hand — so member/form data never has to leave the machine to fill the
 * document, honouring the privacy promise (see CLAUDE.md).
 *
 * The variants carry only layout-shaping hints (label, placeholder, width);
 * the actual answers are never modelled here — they're written on the printed
 * page. [`FormField::into_spec`] turns a variant into the same `(kind, data)`
 * [`BlockSpec`] the program generator emits, so forms persist through the very
 * same `BlockRepo::create` path and render through the same Typst builder.
 */
export type FormField = { "kind": "text_field", label: string, hint: string | null, width: string | null, } | { "kind": "check_box", label: string, } | { "kind": "signature", label: string | null, width: string | null, };
