// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A backward-direction ingest job.
 */
export type ImportJob = { id: string, 
/**
 * Owning project, or `null` for a standalone job.
 */
project_id: string | null, source_path: string, kind: string, 
/**
 * One of: pending | running | done | error.
 */
status: string, 
/**
 * Free-form detail / error message.
 */
detail: string | null, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, };
