/**
 * Type bindings auto-generated by `ts-rs` from Rust types. Do not edit the
 * individual `*.ts` files by hand — they are regenerated by
 * `cargo test export_bindings` (run from `src-tauri/`).
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { AppInfo } from "@/lib/bindings";
 */

export type { AppInfo } from "./AppInfo";
export type { Project } from "./Project";
export type { Document } from "./Document";
export type { Block } from "./Block";
export type { Asset } from "./Asset";
export type { AssetKind } from "./AssetKind";
export type { AssetLibEntry } from "./AssetLibEntry";
export type { Song } from "./Song";
export type { Template } from "./Template";
export type { ImportJob } from "./ImportJob";
export type { Setting } from "./Setting";
export type { PdfInfo } from "./PdfInfo";
export type { PdfPageInfo } from "./PdfPageInfo";

// Document template system (Phase doc-templates).
export type { DocTemplate } from "./DocTemplate";
export type { DocTemplateKind } from "./DocTemplateKind";
export type { TemplateVar } from "./TemplateVar";
export type { TemplateVarKind } from "./TemplateVarKind";

// Sangbok-klipper pipeline (Phase 3.1 OCR prep).
export type { SangbokJob } from "./SangbokJob";
export type { SangbokJobStatus } from "./SangbokJobStatus";
export type { SongExtract } from "./SongExtract";

// ServicePlan → program bridge (services/bulletin.rs).
export type { ServicePlan } from "./ServicePlan";
export type { SetlistItem } from "./SetlistItem";
export type { SetlistItemKind } from "./SetlistItemKind";
export type { SongRef } from "./SongRef";
export type { ScriptureRef } from "./ScriptureRef";
export type { AssetRef } from "./AssetRef";
export type { BlockSpec } from "./BlockSpec";

// Layout engine: block tree → Typst source (services/layout/markup.rs).
export type { LayoutMeta } from "./LayoutMeta";

/** Error shape returned by every Tauri command (see error.rs).
 *  Keep this union in sync with `AppError::code()` in Rust. */
export interface AppError {
  code:
    | "not_found"
    | "validation"
    | "io"
    | "json"
    | "database"
    | "migration"
    | "pdf"
    | "feature_disabled"
    | "internal";
  message: string;
}
