/**
 * Type bindings auto-generated by `ts-rs` from Rust types. Do not edit the
 * individual `*.ts` files by hand — they are regenerated by
 * `cargo test export_bindings` (run from `src-tauri/`).
 *
 * This barrel re-exports everything for ergonomic imports:
 *   import type { AppInfo } from "@/lib/bindings";
 */

export type { AppInfo } from "./AppInfo";
export type { Project } from "./Project";
export type { Document } from "./Document";
export type { Block } from "./Block";
export type { Asset } from "./Asset";
export type { Song } from "./Song";
export type { Template } from "./Template";
export type { ImportJob } from "./ImportJob";
export type { Setting } from "./Setting";

/** Error shape returned by every Tauri command (see error.rs).
 *  Keep this union in sync with `AppError::code()` in Rust. */
export interface AppError {
  code:
    | "not_found"
    | "validation"
    | "io"
    | "json"
    | "database"
    | "migration"
    | "internal";
  message: string;
}
