// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockSpec } from "./BlockSpec";

/**
 * The result of compiling an intent: the ordered specs plus a little metadata
 * the UI can show ("12 blokker, hvorav 1 ukjent type ble droppet").
 */
export type IntentCompileResult = { 
/**
 * The validated, ordered block specs — ready to hand to the same
 * persistence path `bulletin_generate` uses.
 */
blocks: Array<BlockSpec>, 
/**
 * How many blocks the model emitted that we dropped because their `kind`
 * was outside the allowed catalogue. Zero in the happy path; surfaced so
 * the UI can note a degraded result rather than silently losing content.
 */
dropped_unknown_kinds: number, };
