// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A consent-gated, purpose-tagged intent compile request. Built by the command
 * from the user's prompt-bar text plus the persisted consent flag; passed to
 * [`build_request`]. The intent string is the ONLY user content that leaves the
 * machine — there is no field for form/member data, by construction.
 */
export type IntentRequest = { 
/**
 * The free-text intent, e.g. "lag søndagens program for 1. søndag i advent
 * med to salmer og dåp".
 */
intent: string, 
/**
 * Explicit cloud-AI consent. The command sets this from the persisted
 * `cloud_ai_enabled` setting; the builder refuses to produce a request when
 * it is false, so an intent can never be sent without opt-in.
 */
consent: boolean, 
/**
 * Purpose tag carried for auditability / data-minimisation (e.g.
 * "intent_to_layout"). Sent to no third party — it labels the call locally
 * and is echoed into the system prompt's purpose line.
 */
purpose: string | null, 
/**
 * Optional UI language hint (e.g. "no", "en") so the model labels generated
 * blocks in the congregation's language. Defaults to Norwegian.
 */
lang: string | null, };
