// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-church branding applied to the document preamble. Every field is optional
 * so a partial theme (just an accent colour, say) still works and the rest of
 * the look stays at the house default. The values that reach Typst as raw
 * identifiers — font names and the accent colour — are validated/escaped by
 * [`LayoutTheme::resolve`] so a theme can never inject markup or break the
 * compile (a bad value silently falls back to the house default for that one
 * field; the document still renders).
 */
export type LayoutTheme = { 
/**
 * Font family for headings / song titles / the service title. A free-text
 * font name; validated to a safe character set before it reaches Typst.
 */
headingFont: string | null, 
/**
 * Font family for body text (paragraphs, lyrics, scripture). Validated like
 * `heading_font`.
 */
bodyFont: string | null, 
/**
 * Accent colour used for headings / rules — a `#rrggbb` (or `#rgb`) hex
 * string. Validated to a strict hex form before it reaches Typst's `rgb()`.
 */
accentColor: string | null, 
/**
 * Heading weight keyword (`regular` / `medium` / `semibold` / `bold` /
 * `black`). Only this fixed set is accepted; anything else falls back to the
 * house default `bold`.
 */
headingWeight: string | null, 
/**
 * Multiplier on the baseline paragraph leading (line spacing). `1.0` is the
 * house default; clamped to a sane 0.5–3.0 range so a theme can't collapse
 * or explode the layout.
 */
spacingMultiplier: number | null, };
