// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Page metadata for the generated document — drives the Typst `set page` /
 * `set text` preamble. Kept tiny and self-contained so the builder needs no DB
 * row; the caller fills it from the `document` record.
 */
export type LayoutMeta = { 
/**
 * Paper size keyword Typst understands (`a4`, `a5`, `us-letter`, …).
 * Validated/normalised by [`normalize_paper`]; an unknown value falls back
 * to `a4` so the source always compiles.
 */
paper: string, 
/**
 * Base font size in points (clamped to a sane 6–48 pt range).
 */
font_size_pt: number, 
/**
 * Optional default language for Typst hyphenation (`en`, `nb`, `de`, …).
 */
lang: string | null, };
