// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PdfPageInfo } from "./PdfPageInfo";

/**
 * Metadata about a PDF, returned by `pdf_info`.
 */
export type PdfInfo = { 
/**
 * Total number of pages.
 */
page_count: number, 
/**
 * Per-page size in PDF points (1/72 inch). May be empty if sizes could not
 * be read; never partially trusted by callers for layout without a check.
 */
pages: Array<PdfPageInfo>, };
