// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Size of a single page, in PDF points.
 */
export type PdfPageInfo = { width_pt: number, height_pt: number, };
