// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project: a named container grouping related documents and their work.
 */
export type Project = { id: string, name: string, description: string, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, 
/**
 * Unix milliseconds, set when soft-deleted; `null` while live.
 */
deleted_at: bigint | null, };
