// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SongExtract } from "./SongExtract";

/**
 * An OCR pipeline job for a scanned hymnal PDF.
 */
export type SangbokJob = { id: string, input_pdf_path: string, status: string, 
/**
 * Page count as reported by the PDF reader (0 until determined).
 */
page_count: number, songs_found: Array<SongExtract>, 
/**
 * Detail / error message — `None` while still running.
 */
error_detail: string | null, created_at: bigint, updated_at: bigint, };
