// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to a scripture passage (e.g. "John 3:16-21").
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type ScriptureRef = { 
/**
 * Bible book, e.g. "John".
 */
book: string | null, 
/**
 * Chapter / verse reference, e.g. "3:16-21".
 */
reference: string | null, 
/**
 * Translation / version, e.g. "NRSV", "Bibel 2011".
 */
translation: string | null, };
