// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetlistItem } from "./SetlistItem";

/**
 * A whole planned service: header metadata + the ordered items.
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type ServicePlan = { 
/**
 * Service title, e.g. "Sunday Worship".
 */
title: string | null, 
/**
 * Congregation / parish name, printed as a subtitle.
 */
church: string | null, 
/**
 * Human date string as the plan supplied it (e.g. "1 June 2026"). We carry
 * it through verbatim rather than reformatting — the plan owns the locale.
 */
date: string | null, 
/**
 * Ordered service items.
 */
items: Array<SetlistItem>, };
