// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptureRef } from "./ScriptureRef";
import type { SetlistItemKind } from "./SetlistItemKind";
import type { SongRef } from "./SongRef";

/**
 * One ordered item in a service plan.
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type SetlistItem = { kind: SetlistItemKind, 
/**
 * Item title / label, e.g. "Welcome", the song title, "First Reading".
 */
title: string | null, 
/**
 * Free body text — sermon synopsis, announcement text, liturgy lines.
 */
body: string | null, 
/**
 * Who leads / speaks this item, printed as a byline.
 */
leader: string | null, 
/**
 * Present when `kind == Song`.
 */
song: SongRef | null, 
/**
 * Present when `kind == Scripture`.
 */
scripture: ScriptureRef | null, };
