// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetRef } from "./AssetRef";
import type { ScriptureRef } from "./ScriptureRef";
import type { SetlistItemKind } from "./SetlistItemKind";
import type { SongRef } from "./SongRef";

/**
 * One ordered item in a service plan.
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type SetlistItem = { kind: SetlistItemKind, 
/**
 * Item title / label, e.g. "Welcome", the song title, "First Reading".
 */
title: string | null, 
/**
 * Free body text — sermon synopsis, announcement text, liturgy lines.
 */
body: string | null, 
/**
 * Who leads / speaks this item, printed as a byline.
 */
leader: string | null, 
/**
 * A clock time the plan attached (e.g. "10:30"), printed in the margin so
 * a printed order-of-service can double as a run sheet.
 */
time: string | null, 
/**
 * Rights line for printed song lyrics (e.g. a CCLI / copyright credit).
 * Carried so a song block can print the credit the licence requires — the
 * Nordic TONO/CCLI reality from the product principles.
 */
copyright: string | null, 
/**
 * When true the renderer should start this item on a fresh page (e.g. a
 * full-page hymn sheet). Defaults to false.
 */
page_break: boolean, 
/**
 * Present when `kind == Song`.
 */
song: SongRef | null, 
/**
 * Present when `kind == Scripture`.
 */
scripture: ScriptureRef | null, 
/**
 * Present when `kind == Image`.
 */
asset: AssetRef | null, };
