// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a single ordered item in a service plan.
 *
 * Mirrors `sunday-contracts`; converge once published. Unknown / future kinds
 * deserialise to [`SetlistItemKind::Other`] (via `#[serde(other)]`) so a
 * newer SundayPlan can add item kinds without breaking this generator — they
 * fall back to a plain text block rather than being dropped.
 */
export type SetlistItemKind = "welcome" | "song" | "scripture" | "sermon" | "liturgy" | "prayer" | "announcement" | "offering" | "benediction" | "other";
