// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single key/value setting.
 */
export type Setting = { key: string, value: string, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, };
