// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A song found (or hypothesised) within a sangbok PDF.
 */
export type SongExtract = { id: string, job_id: string, 
/**
 * First page (0-indexed) in the source PDF.
 */
page_start: number, 
/**
 * Last page (inclusive) in the source PDF.
 */
page_end: number, 
/**
 * Best-guess song title from OCR text or heuristic.
 */
title_hint: string, 
/**
 * OCR/heuristic confidence ∈ [0.0, 1.0].
 */
confidence: number, position: bigint, };
