// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A song in the catalog.
 */
export type Song = { id: string, title: string, author: string | null, body: string, language: string | null, tono_work_id: string | null, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, 
/**
 * Unix milliseconds, set when soft-deleted; `null` while live.
 */
deleted_at: bigint | null, };
