// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to a song in the catalog, carried through from the plan so the
 * generated block can later be re-bound to the live `song` row / lyrics.
 *
 * Mirrors `sunday-contracts`; converge once published.
 */
export type SongRef = { 
/**
 * SundaySong / catalog id, if the plan knew one. Carried verbatim so the
 * block can relink to the local catalog row.
 */
song_id: string | null, 
/**
 * TONO work id — the Nordic rights identifier. Carried "from day one" per
 * the product principle even though we don't print it.
 */
tono_work_id: string | null, 
/**
 * Author / composer, if known.
 */
author: string | null, 
/**
 * Hymnal / songbook number (e.g. "N13 097"), printed next to the title.
 */
number: string | null, 
/**
 * The song's verses, in singing order — one entry per verse (a verse may
 * itself span several lines). Carried when the plan is bound to the song
 * catalog so the program prints the actual words, not just the heading.
 * Empty / absent means a bare reference (heading only), as before.
 */
verses: Array<string>, 
/**
 * The refrain / chorus, printed once after the first verse. `None` when the
 * song has no refrain.
 */
refrain: string | null, };
