// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable layout template.
 */
export type Template = { id: string, name: string, kind: string, 
/**
 * Typst source; empty until Phase 4.2.
 */
source: string, 
/**
 * Unix milliseconds.
 */
created_at: bigint, 
/**
 * Unix milliseconds.
 */
updated_at: bigint, 
/**
 * Unix milliseconds, set when soft-deleted; `null` while live.
 */
deleted_at: bigint | null, };
