// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A typed variable declaration inside a document template.
 */
export type TemplateVar = { id: string, template_id: string, 
/**
 * Key used as `{{name}}` placeholder in the Typst source.
 */
name: string, 
/**
 * Human-readable label shown in the fill-in UI.
 */
label: string, 
/**
 * What type of value this variable accepts.
 */
kind: string, default_value: string | null, 
/**
 * Whether a value must be provided before rendering.
 */
required: boolean, position: bigint, created_at: bigint, };
