// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data type of a template variable.
 */
export type TemplateVarKind = "Text" | "Number" | "Date" | "Boolean" | "SongList" | "ScriptureRef";
