// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a template variable.
 */
export type TemplateVarInput = { name: string, label: string, kind: string, default_value: string | null, required: boolean, };
