//! Pure block-tree → Typst source-string builder — the deterministic half of
//! the layout engine (Phase 4.2).
//!
//! Producing a PDF is two steps: (1) turn the document's block tree into a
//! **Typst source string**, then (2) hand that string to the Typst compiler.
//! Step (2) needs the embedded compiler crate and so stays behind the `typst`
//! cargo feature (see `layout::engine`, INFRA-UNVERIFIED). Step (1) is plain
//! string assembly — no compiler, no I/O — so it lives here, is always
//! compiled, and is exhaustively unit-tested. Same posture as `pdf::plan`.
//!
//! The builder consumes the exact JSON payloads the `bulletin` generator emits
//! (`heading` / `song` / `music` / `scripture` / `liturgy` / `announcement` /
//! `image` / `text`), so the FORWARD pipeline composes end to end:
//!
//! ```text
//! ServicePlan --build_bulletin--> BlockSpec[] --(persist)--> Block tree
//!             --build_typst_document--> Typst source --(compile)--> PDF
//! ```
//!
//! Two design rules make the output trustworthy without rendering it:
//! 1. **Everything user-supplied is escaped** via [`escape_content`] before it
//!    reaches the source, so a song title with a `#` or `$` can never inject
//!    Typst markup or break compilation.
//! 2. The emitted source is **deterministic** — the same tree always yields the
//!    same bytes — so tests can assert on it directly.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Page metadata for the generated document — drives the Typst `set page` /
/// `set text` preamble. Kept tiny and self-contained so the builder needs no DB
/// row; the caller fills it from the `document` record.
#[derive(Debug, Clone, Serialize, Deserialize, TS, PartialEq)]
#[ts(export, export_to = "../../src/lib/bindings/LayoutMeta.ts")]
pub struct LayoutMeta {
    /// Paper size keyword Typst understands (`a4`, `a5`, `us-letter`, …).
    /// Validated/normalised by [`normalize_paper`]; an unknown value falls back
    /// to `a4` so the source always compiles.
    pub paper: String,
    /// Base font size in points (clamped to a sane 6–48 pt range).
    pub font_size_pt: f64,
    /// Optional default language for Typst hyphenation (`en`, `nb`, `de`, …).
    pub lang: Option<String>,
}

impl Default for LayoutMeta {
    fn default() -> Self {
        Self {
            paper: "a4".into(),
            font_size_pt: 11.0,
            lang: None,
        }
    }
}

/// A node in the tree handed to the builder. Mirrors a persisted `block` row
/// stripped to what layout needs (`kind` + parsed `data` + `children`), so the
/// builder stays free of the DB types and is trivially constructed in tests.
#[derive(Debug, Clone, PartialEq)]
pub struct RenderBlock {
    pub kind: String,
    /// Parsed block payload (the `data` JSON column, already deserialised).
    pub data: serde_json::Value,
    pub children: Vec<RenderBlock>,
}

impl RenderBlock {
    /// Build a leaf node from a kind and a JSON payload.
    pub fn leaf(kind: &str, data: serde_json::Value) -> Self {
        Self {
            kind: kind.to_string(),
            data,
            children: Vec::new(),
        }
    }

    /// Convenience for tests / callers: parse a `(kind, data_json_str)` pair —
    /// exactly the `BlockSpec` shape — into a leaf, defaulting unparsable or
    /// empty data to an empty object so the builder never panics.
    pub fn from_spec(kind: &str, data_json: &str) -> Self {
        let data = serde_json::from_str(data_json).unwrap_or(serde_json::Value::Null);
        let data = if data.is_object() {
            data
        } else {
            serde_json::json!({})
        };
        Self::leaf(kind, data)
    }
}

/// Assemble a complete, self-contained Typst document source string from page
/// metadata and an ordered block tree.
///
/// The output is a preamble (`set page` / `set text` / a couple of reusable
/// helper functions) followed by one rendered chunk per top-level block, in
/// order. The result is pure markup — feed it to the compiler to get a PDF.
pub fn build_typst_document(meta: &LayoutMeta, blocks: &[RenderBlock]) -> String {
    let mut out = String::with_capacity(512 + blocks.len() * 64);
    out.push_str(&preamble(meta));
    for block in blocks {
        out.push_str(&render_block(block));
    }
    out
}

/// The document preamble: page + text setup and the small set of helper
/// functions the per-block markup calls (`#bp-heading`, `#bp-byline`, …).
fn preamble(meta: &LayoutMeta) -> String {
    let paper = normalize_paper(&meta.paper);
    let size = clamp_font_size(meta.font_size_pt);
    let lang_line = match meta.lang.as_deref().map(str::trim).filter(|s| !s.is_empty()) {
        Some(lang) => format!(", lang: \"{}\"", escape_string(lang)),
        None => String::new(),
    };
    format!(
        "// Generated by SundayPaper — do not edit by hand.\n\
         #set page(paper: \"{paper}\", margin: 2cm)\n\
         #set text(size: {size}pt{lang_line})\n\
         #set par(justify: false, leading: 0.65em)\n\n\
         // --- reusable helpers ---\n\
         #let bp-title(t, sub: none, date: none) = {{\n  \
             align(center)[#text(size: 1.6em, weight: \"bold\")[#t]]\n  \
             if sub != none {{ align(center)[#text(size: 1.1em)[#sub]] }}\n  \
             if date != none {{ align(center)[#emph[#date]] }}\n  \
             v(0.4em); line(length: 100%); v(0.6em)\n\
         }}\n\
         #let bp-heading(t) = [#v(0.5em)#text(size: 1.2em, weight: \"bold\")[#t]#v(0.2em)]\n\
         #let bp-byline(who) = if who != none {{ text(size: 0.85em, style: \"italic\")[#who] }}\n\
         #let bp-time(t) = if t != none {{ box(width: 3em)[#text(fill: gray)[#t]] }}\n\n",
    )
}

/// Render one block (and recurse into its children). Dispatches on `kind`;
/// unknown kinds degrade to the generic text renderer so nothing is dropped —
/// the same "never lose a block" promise the bulletin generator makes.
fn render_block(block: &RenderBlock) -> String {
    let d = &block.data;
    let mut s = String::new();

    // Cross-cutting hint: a leading page break, if the block asked for one.
    if d.get("pageBreak").and_then(serde_json::Value::as_bool) == Some(true) {
        s.push_str("#pagebreak()\n");
    }

    match block.kind.as_str() {
        "heading" => s.push_str(&render_heading(d)),
        "song" => s.push_str(&render_song(d)),
        "music" => s.push_str(&render_music(d)),
        "scripture" => s.push_str(&render_scripture(d)),
        "liturgy" => s.push_str(&render_liturgy(d)),
        "announcement" => s.push_str(&render_announcement(d)),
        "image" => s.push_str(&render_image(d)),
        // "text" and any unknown future kind.
        _ => s.push_str(&render_text(d)),
    }

    for child in &block.children {
        s.push_str(&render_block(child));
    }
    s.push('\n');
    s
}

/// `heading` — either the leading service title (role `service-title`, with the
/// subtitle/date helper) or a plain section heading (e.g. the sermon).
fn render_heading(d: &serde_json::Value) -> String {
    let title = field(d, "title");
    if role(d) == "service-title" {
        return format!(
            "#bp-title({}, sub: {}, date: {})\n",
            content_arg(&title),
            content_arg(&field(d, "subtitle")),
            content_arg(&field(d, "date")),
        );
    }
    let mut s = format!("#bp-heading({})\n", content_arg(&title));
    // A sermon heading may carry a preacher byline + synopsis.
    if let Some(p) = field(d, "preacher") {
        s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(p))));
    }
    if let Some(syn) = field(d, "synopsis") {
        s.push_str(&format!("#par[{}]\n", escape_content(&syn)));
    }
    s
}

/// `song` — title (+ hymnal number), an optional author byline and an optional
/// copyright credit printed small under the title. Lyrics aren't carried in the
/// plan, so the block prints the heading the program needs; the editor binds
/// full lyrics later.
fn render_song(d: &serde_json::Value) -> String {
    let title = field(d, "title").unwrap_or_else(|| "Song".to_string());
    let heading = match field(d, "number") {
        Some(n) => format!("{} — {}", n, title),
        None => title,
    };
    let mut s = format!("#bp-heading({})\n", content_arg(&Some(heading)));
    if let Some(author) = field(d, "author") {
        s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(author))));
    }
    if let Some(c) = field(d, "copyright") {
        s.push_str(&format!(
            "#text(size: 0.75em, fill: gray)[{}]\n",
            escape_content(&c)
        ));
    }
    s
}

/// `music` — instrumental: a heading plus an optional performer byline / note.
fn render_music(d: &serde_json::Value) -> String {
    let title = field(d, "title").unwrap_or_else(|| "Music".to_string());
    let mut s = format!("#bp-heading({})\n", content_arg(&Some(title)));
    if let Some(leader) = field(d, "leader") {
        s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(leader))));
    }
    if let Some(note) = field(d, "text") {
        s.push_str(&format!("#emph[{}]\n", escape_content(&note)));
    }
    s
}

/// `scripture` — a heading (title or the "Book ref" reference), a reader byline
/// and the read text as a quote block.
fn render_scripture(d: &serde_json::Value) -> String {
    let reference = join_reference(d);
    let heading = field(d, "title").or_else(|| reference.clone());
    let mut s = format!(
        "#bp-heading({})\n",
        content_arg(&heading.or_else(|| Some("Reading".to_string())))
    );
    // If the heading was a custom title, still print the reference under it.
    if field(d, "title").is_some() {
        if let Some(r) = reference {
            s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(r))));
        }
    }
    if let Some(reader) = field(d, "reader") {
        s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(reader))));
    }
    if let Some(text) = field(d, "text") {
        s.push_str(&format!("#quote(block: true)[{}]\n", escape_content(&text)));
    }
    s
}

/// `liturgy` — a labelled spoken element with an optional leader byline + text.
fn render_liturgy(d: &serde_json::Value) -> String {
    let title = field(d, "title").unwrap_or_else(|| "Liturgy".to_string());
    let mut s = format!("#bp-heading({})\n", content_arg(&Some(title)));
    if let Some(leader) = field(d, "leader") {
        s.push_str(&format!("#bp-byline({})\n", content_arg(&Some(leader))));
    }
    if let Some(text) = field(d, "text") {
        s.push_str(&format!("#par[{}]\n", escape_content(&text)));
    }
    s
}

/// `announcement` — a heading + body paragraph.
fn render_announcement(d: &serde_json::Value) -> String {
    let title = field(d, "title").unwrap_or_else(|| "Announcement".to_string());
    let mut s = format!("#bp-heading({})\n", content_arg(&Some(title)));
    if let Some(text) = field(d, "text") {
        s.push_str(&format!("#par[{}]\n", escape_content(&text)));
    }
    s
}

/// `image` — an embedded image with an optional caption. The path comes from
/// the asset's local `url`; if there is no path we emit a caption-only
/// placeholder rather than an `image()` call that would fail to compile.
fn render_image(d: &serde_json::Value) -> String {
    let caption = field(d, "caption").or_else(|| field(d, "title"));
    match field(d, "url") {
        Some(path) => {
            let img = format!("image(\"{}\", width: 80%)", escape_string(&path));
            match caption {
                Some(c) => format!(
                    "#figure({}, caption: [{}])\n",
                    img,
                    escape_content(&c)
                ),
                None => format!("#align(center)[#{}]\n", img),
            }
        }
        None => match caption {
            Some(c) => format!("#align(center)[#emph[{}]]\n", escape_content(&c)),
            None => String::new(),
        },
    }
}

/// `text` and the fallback for unknown kinds — an optional bold title + body.
fn render_text(d: &serde_json::Value) -> String {
    let mut s = String::new();
    if let Some(title) = field(d, "title") {
        s.push_str(&format!("#bp-heading({})\n", content_arg(&Some(title))));
    }
    if let Some(text) = field(d, "text") {
        s.push_str(&format!("#par[{}]\n", escape_content(&text)));
    }
    s
}

// --- payload helpers ---------------------------------------------------------

/// Read a string field from a payload, returning `None` for absent / null /
/// non-string / blank values (so the markup never prints empty constructs).
fn field(d: &serde_json::Value, key: &str) -> Option<String> {
    d.get(key)
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
}

/// The `role` discriminator a block may carry (heading/liturgy), defaulting to
/// an empty string when absent.
fn role(d: &serde_json::Value) -> &str {
    d.get("role").and_then(serde_json::Value::as_str).unwrap_or("")
}

/// Build the "Book chapter:verse (Translation)" reference string from a
/// scripture payload, or `None` if there is nothing to show.
fn join_reference(d: &serde_json::Value) -> Option<String> {
    let book = field(d, "book");
    let reference = field(d, "reference");
    let base = match (book, reference) {
        (Some(b), Some(r)) => Some(format!("{} {}", b, r)),
        (Some(b), None) => Some(b),
        (None, Some(r)) => Some(r),
        (None, None) => None,
    }?;
    match field(d, "translation") {
        Some(t) => Some(format!("{} ({})", base, t)),
        None => Some(base),
    }
}

// --- Typst escaping ----------------------------------------------------------

/// Turn an `Option<String>` into a Typst function-call argument: a bracketed
/// content block `[...]` with escaped contents, or the literal `none` when the
/// value is absent. Used for every helper call so callers stay readable.
fn content_arg(value: &Option<String>) -> String {
    match value {
        Some(v) => format!("[{}]", escape_content(v)),
        None => "none".to_string(),
    }
}

/// Escape arbitrary user text for Typst **content (markup) mode**.
///
/// Typst markup gives meaning to a handful of leading / inline characters
/// (`\ # $ * _ \` < > @ ~ [ ]` plus structural `/ - + =`). To guarantee that a
/// title like `#1 — A*B` prints verbatim and can never inject markup or break
/// compilation, we backslash-escape every character Typst treats specially.
/// Newlines are converted to a hard line break (`\ ` then newline) so multi-line
/// liturgy text keeps its lines.
pub fn escape_content(input: &str) -> String {
    let mut out = String::with_capacity(input.len() + 8);
    for ch in input.chars() {
        match ch {
            // Backslash first so we don't double-escape what follows.
            '\\' => out.push_str("\\\\"),
            '#' | '$' | '*' | '_' | '`' | '<' | '>' | '@' | '~' | '[' | ']' | '/' | '=' => {
                out.push('\\');
                out.push(ch);
            }
            '\n' => out.push_str("\\\n"),
            '\r' => {} // drop bare CR; the paired \n carries the break
            _ => out.push(ch),
        }
    }
    out
}

/// Escape a string destined for a Typst **string literal** (double-quoted), as
/// in `image("...")` or `lang: "..."`. Only the backslash and the double quote
/// need escaping inside a Typst string; control chars are dropped.
pub fn escape_string(input: &str) -> String {
    let mut out = String::with_capacity(input.len() + 4);
    for ch in input.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' | '\r' | '\t' => {} // never legal raw in a single-line literal
            _ => out.push(ch),
        }
    }
    out
}

/// Normalise a paper keyword to one Typst accepts; unknown values fall back to
/// `a4` so the generated source always compiles. Case-insensitive.
fn normalize_paper(paper: &str) -> String {
    match paper.trim().to_ascii_lowercase().as_str() {
        "a3" => "a3",
        "a4" => "a4",
        "a5" => "a5",
        "a6" => "a6",
        "us-letter" | "letter" => "us-letter",
        "us-legal" | "legal" => "us-legal",
        _ => "a4",
    }
    .to_string()
}

/// Clamp the font size into a sane printable range (6–48 pt); NaN → default.
fn clamp_font_size(pt: f64) -> f64 {
    if pt.is_finite() {
        pt.clamp(6.0, 48.0)
    } else {
        11.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn doc(blocks: &[RenderBlock]) -> String {
        build_typst_document(&LayoutMeta::default(), blocks)
    }

    #[test]
    fn preamble_sets_page_and_text() {
        let src = build_typst_document(&LayoutMeta::default(), &[]);
        assert!(src.contains("#set page(paper: \"a4\", margin: 2cm)"));
        assert!(src.contains("#set text(size: 11pt)"));
        assert!(src.contains("#let bp-title"));
        // No blocks → preamble only, no trailing block markup.
        assert!(!src.contains("#bp-heading("));
    }

    #[test]
    fn unknown_paper_falls_back_to_a4_and_font_clamps() {
        let meta = LayoutMeta {
            paper: "tabloid".into(),
            font_size_pt: 500.0,
            lang: Some("nb".into()),
        };
        let src = build_typst_document(&meta, &[]);
        assert!(src.contains("paper: \"a4\""));
        assert!(src.contains("size: 48pt"), "font clamped to max 48");
        assert!(src.contains("lang: \"nb\""));
    }

    #[test]
    fn nan_font_size_uses_default() {
        let meta = LayoutMeta {
            font_size_pt: f64::NAN,
            ..LayoutMeta::default()
        };
        assert!(build_typst_document(&meta, &[]).contains("size: 11pt"));
    }

    #[test]
    fn service_title_uses_title_helper_with_sub_and_date() {
        let b = RenderBlock::leaf(
            "heading",
            json!({
                "role": "service-title",
                "title": "Sunday Worship",
                "subtitle": "St. Olav's",
                "date": "1 June 2026",
            }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-title([Sunday Worship], sub: [St. Olav's], date: [1 June 2026])"));
    }

    #[test]
    fn service_title_omits_missing_sub_and_date_as_none() {
        let b = RenderBlock::leaf(
            "heading",
            json!({ "role": "service-title", "title": "Worship" }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-title([Worship], sub: none, date: none)"));
    }

    #[test]
    fn sermon_heading_carries_preacher_and_synopsis() {
        let b = RenderBlock::leaf(
            "heading",
            json!({
                "role": "sermon",
                "title": "The Light",
                "preacher": "Pastor Anne",
                "synopsis": "On living in the light.",
            }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([The Light])"));
        assert!(src.contains("#bp-byline([Pastor Anne])"));
        assert!(src.contains("#par[On living in the light.]"));
    }

    #[test]
    fn song_prefixes_number_and_prints_author_and_copyright() {
        let b = RenderBlock::leaf(
            "song",
            json!({
                "title": "Holy, Holy, Holy",
                "number": "N13 097",
                "author": "Reginald Heber",
                "copyright": "Public Domain",
            }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([N13 097 — Holy, Holy, Holy])"));
        assert!(src.contains("#bp-byline([Reginald Heber])"));
        assert!(src.contains("#text(size: 0.75em, fill: gray)[Public Domain]"));
    }

    #[test]
    fn song_without_number_uses_bare_title() {
        let b = RenderBlock::leaf("song", json!({ "title": "Amazing Grace" }));
        assert!(doc(&[b]).contains("#bp-heading([Amazing Grace])"));
    }

    #[test]
    fn music_block_renders_heading_byline_and_note() {
        let b = RenderBlock::leaf(
            "music",
            json!({ "title": "Postlude", "leader": "Organist", "text": "Bach" }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([Postlude])"));
        assert!(src.contains("#bp-byline([Organist])"));
        assert!(src.contains("#emph[Bach]"));
    }

    #[test]
    fn scripture_builds_reference_with_translation() {
        let b = RenderBlock::leaf(
            "scripture",
            json!({
                "book": "John",
                "reference": "3:16-21",
                "translation": "NRSV",
                "text": "For God so loved the world.",
            }),
        );
        let src = doc(&[b]);
        // No explicit title → the reference becomes the heading.
        assert!(src.contains("#bp-heading([John 3:16-21 (NRSV)])"));
        assert!(src.contains("#quote(block: true)[For God so loved the world.]"));
    }

    #[test]
    fn scripture_with_title_shows_reference_as_byline() {
        let b = RenderBlock::leaf(
            "scripture",
            json!({ "title": "First Reading", "book": "John", "reference": "3:16" }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([First Reading])"));
        assert!(src.contains("#bp-byline([John 3:16])"));
    }

    #[test]
    fn liturgy_renders_title_leader_and_text() {
        let b = RenderBlock::leaf(
            "liturgy",
            json!({ "role": "benediction", "title": "Benediction", "leader": "Pastor", "text": "Go in peace." }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([Benediction])"));
        assert!(src.contains("#bp-byline([Pastor])"));
        assert!(src.contains("#par[Go in peace.]"));
    }

    #[test]
    fn image_with_url_becomes_figure_with_caption() {
        let b = RenderBlock::leaf(
            "image",
            json!({ "url": "/assets/banner.png", "caption": "He is risen" }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#figure(image(\"/assets/banner.png\", width: 80%), caption: [He is risen])"));
    }

    #[test]
    fn image_without_url_emits_caption_placeholder_not_broken_image() {
        let b = RenderBlock::leaf("image", json!({ "caption": "Missing art" }));
        let src = doc(&[b]);
        assert!(!src.contains("image("), "no image() call without a path");
        assert!(src.contains("#align(center)[#emph[Missing art]]"));
    }

    #[test]
    fn image_without_url_or_caption_emits_nothing() {
        let b = RenderBlock::leaf("image", json!({}));
        let src = doc(&[b]);
        // Only the preamble and a trailing newline from the block separator.
        assert!(!src.contains("image"));
        assert!(!src.contains("#align"));
    }

    #[test]
    fn text_block_and_unknown_kind_use_text_renderer() {
        let known = RenderBlock::leaf("text", json!({ "title": "Notes", "text": "hello" }));
        let unknown = RenderBlock::leaf("totally_new", json!({ "title": "Mystery", "text": "x" }));
        let src = doc(&[known, unknown]);
        assert!(src.contains("#bp-heading([Notes])"));
        assert!(src.contains("#par[hello]"));
        // Unknown kind is not dropped — it renders through the text path.
        assert!(src.contains("#bp-heading([Mystery])"));
        assert!(src.contains("#par[x]"));
    }

    #[test]
    fn page_break_hint_emits_pagebreak_before_block() {
        let b = RenderBlock::leaf(
            "song",
            json!({ "title": "Hymn", "pageBreak": true }),
        );
        let src = doc(&[b]);
        let pb = src.find("#pagebreak()").expect("pagebreak emitted");
        let heading = src.find("#bp-heading([Hymn])").expect("heading emitted");
        assert!(pb < heading, "pagebreak comes before the block content");
    }

    #[test]
    fn no_page_break_when_flag_absent_or_false() {
        let absent = RenderBlock::leaf("text", json!({ "text": "a" }));
        let falsey = RenderBlock::leaf("text", json!({ "text": "b", "pageBreak": false }));
        let src = doc(&[absent, falsey]);
        assert!(!src.contains("#pagebreak()"));
    }

    #[test]
    fn children_render_after_their_parent() {
        let parent = RenderBlock {
            kind: "liturgy".into(),
            data: json!({ "title": "Section" }),
            children: vec![RenderBlock::leaf("text", json!({ "text": "child line" }))],
        };
        let src = doc(&[parent]);
        let p = src.find("#bp-heading([Section])").unwrap();
        let c = src.find("#par[child line]").unwrap();
        assert!(p < c, "parent markup precedes its child");
    }

    #[test]
    fn order_of_top_level_blocks_is_preserved() {
        let src = doc(&[
            RenderBlock::leaf("text", json!({ "title": "First" })),
            RenderBlock::leaf("text", json!({ "title": "Second" })),
        ]);
        assert!(src.find("[First]").unwrap() < src.find("[Second]").unwrap());
    }

    #[test]
    fn build_is_deterministic() {
        let blocks = [RenderBlock::leaf(
            "scripture",
            json!({ "book": "John", "reference": "1:1", "text": "In the beginning" }),
        )];
        let a = doc(&blocks);
        let b = doc(&blocks);
        assert_eq!(a, b, "same tree → identical source bytes");
    }

    // --- escaping -------------------------------------------------------------

    #[test]
    fn content_escaping_neutralises_markup_chars() {
        // Every special char gets a leading backslash; text can't inject markup.
        let raw = "#1 *bold* _it_ `code` <a> @x ~ [b] / = $ \\";
        let esc = escape_content(raw);
        assert_eq!(
            esc,
            "\\#1 \\*bold\\* \\_it\\_ \\`code\\` \\<a\\> \\@x \\~ \\[b\\] \\/ \\= \\$ \\\\"
        );
    }

    #[test]
    fn content_escaping_handles_newlines_as_hard_breaks() {
        assert_eq!(escape_content("line1\nline2"), "line1\\\nline2");
        // CRLF: the CR is dropped, the LF becomes the break.
        assert_eq!(escape_content("a\r\nb"), "a\\\nb");
    }

    #[test]
    fn injected_title_cannot_escape_its_content_block() {
        // A malicious title trying to close the [ ] and inject a function.
        let b = RenderBlock::leaf("text", json!({ "title": "x] #panic() [y" }));
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([x\\] \\#panic\\(\\)... "[..18].trim_end()));
        // More precisely: the brackets and # are escaped, so the [..] stays whole.
        assert!(src.contains("\\]"));
        assert!(src.contains("\\#panic"));
        assert!(!src.contains("[x] #panic"));
    }

    #[test]
    fn string_escaping_handles_quotes_and_backslashes() {
        assert_eq!(escape_string(r#"a"b\c"#), r#"a\"b\\c"#);
        // Newlines/tabs are stripped (never legal raw in a Typst string literal).
        assert_eq!(escape_string("a\nb\tc"), "abc");
    }

    #[test]
    fn image_path_with_quote_is_escaped_in_string_literal() {
        let b = RenderBlock::leaf("image", json!({ "url": "a\"b.png", "caption": "c" }));
        let src = doc(&[b]);
        assert!(src.contains("image(\"a\\\"b.png\", width: 80%)"));
    }

    #[test]
    fn blank_and_null_fields_are_ignored() {
        let b = RenderBlock::leaf(
            "liturgy",
            json!({ "title": "Prayer", "leader": "   ", "text": null }),
        );
        let src = doc(&[b]);
        assert!(src.contains("#bp-heading([Prayer])"));
        assert!(!src.contains("#bp-byline"), "blank leader → no byline");
        assert!(!src.contains("#par["), "null text → no paragraph");
    }

    #[test]
    fn from_spec_parses_json_and_defaults_bad_data_to_empty_object() {
        assert_eq!(
            RenderBlock::from_spec("text", r#"{"title":"T"}"#).data,
            json!({ "title": "T" })
        );
        // Garbage / non-object data degrades to {} rather than panicking.
        assert_eq!(RenderBlock::from_spec("text", "not json").data, json!({}));
        assert_eq!(RenderBlock::from_spec("text", "[1,2]").data, json!({}));
    }
}
